# Generated by Django 4.0.4 on 2022-05-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_cartitems_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instamoji_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItems', to='Home.cart'),
        ),
    ]
